-- Setup banco ERPCOZ
CREATE DATABASE IF NOT EXISTS erpcoz;
CREATE USER IF NOT EXISTS erpcoz WITH PASSWORD 'erpcozpass';
ALTER USER erpcoz CREATEDB;
GRANT ALL PRIVILEGES ON DATABASE erpcoz TO erpcoz;
